### ISSUE TITLE
May not work on long streets with different schedules

### ISSUE THREAD

**Issue by rolandsteinmeyer** [tuxuser/abfallapi_regioit_ha#10]
Long Streets in larger cities may have different schedules dependant on street number. This is currently not implemented. See also [https://github.com/bundesAPI/abfallnavi-api]

**Comment by tuxuser** [comment]
Thanks for pointing me to this library, it did not exist when this HA addon / library was created.
Same goes for the HACS integration: https://github.com/mampfes/hacs_waste_collection_schedule

That said, I do not really see the need to maintaining / extending this codebase here anymore if there is an actively maintained and feature-richer solution available.

UPDATE: Extended the README with a link to the newer plugin.
