### ISSUE TITLE
[custom_components.abfallapi_regioit.sensor] No street with name

### ISSUE THREAD

**Issue by northpower25** [tuxuser/abfallapi_regioit_ha#3]
at first great work! but i've got the following error `[custom_components.abfallapi_regioit.sensor] No street with name Kaltenweide 1 - 156`

but i see the street name in the resource link -

[https://pi-abfallapp.regioit.de/abfall-app-pi/rest/orte/4888298/strassen](https://pi-abfallapp.regioit.de/abfall-app-pi/rest/orte/4888298/strassen)

`<strasse>
<id>4888546</id>
<name>Kaltenweide 1 - 156</name>
<ort>
<id>4888298</id>
<name>Elmshorn</name>`

My config in configuration.yaml

> sensor:
>   - platform: abfallapi_regioit
>     name: muellabfuhr
>     scan_interval: 3600
>     anbieter_id: Pinneberg
>     ort: 'Elmshorn'
>     strasse: 'Kaltenweide 1 - 156'

any idea what's going wrong?

if it is possible, it would be great if you could make an GUI for the configuration of this great integration.

**Comment by tuxuser** [comment]
Found the issue
This is example json output for ``
```json
  {
    "id": 4888546,
    "name": "Kaltenweide     1 - 156",
    "hausNrList": [],
    "ort": {
      "id": 4888298,
      "name": "Elmshorn"
    }
  }
```
Notice the unnecessary whitespaces? No clue why the data is formatted like that, but it is solvable by replacing multiple whitespaces with a single one

**Comment by tuxuser** [comment]
Fixed
