### ISSUE TITLE
Andere Regionen

### ISSUE THREAD

**Issue by Acey-yo** [tuxuser/abfallapi_regioit_ha#5]
Hallo, 

ist es evt. möglich, auch die Daten vom Kreis Segeberg(Wege Zweckverband"WZV") mit zu intigrieren?

Wäre toll, wenn es eine Möglichkeit geben würde. 

Lg

**Comment by tuxuser** [comment]
Hey,

Es sieht nicht so aus als würde diese Anbieter von regioIT unterstützt werden.

https://play.google.com/store/apps/developer?id=regio+iT&hl=en_US

Hier siehst du welche Bezirke von der API der regioIT supported sind.

Gruß

**Comment by Acey-yo** [comment]
Hey, 

ok das ist sehr schade. Auch andere Integrationen gehen auch noch nicht. 
Dennoch super Arbeit und vielen dank für die schnelle Antwort.

Lg
