### ISSUE TITLE
Version Key is missing in the manifest file

### ISSUE THREAD

**Issue by ggruner** [tuxuser/abfallapi_regioit_ha#6]
I have updated Home Assistant to version 2021.3.1 and I see the following warning in the logs.

No 'version' key in the manifest file for custom integration 'abfallapi_regioit'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'abfallapi_regioit'.

It would be nice if this will be fixed, that we can use this good custom integration also in the future in HA.

**Comment by tuxuser** [comment]
Done with 67f494a

**Comment by ggruner** [comment]
Thanks for the quick fix.
